require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnalisisRsdsController do

  # This should return the minimal set of attributes required to create a valid
  # AnalisisRsd. As you add validations to AnalisisRsd, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "fecha_extraccion" => "2013-10-02" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnalisisRsdsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all analisis_rsds as @analisis_rsds" do
      analisis_rsd = AnalisisRsd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:analisis_rsds).should eq([analisis_rsd])
    end
  end

  describe "GET show" do
    it "assigns the requested analisis_rsd as @analisis_rsd" do
      analisis_rsd = AnalisisRsd.create! valid_attributes
      get :show, {:id => analisis_rsd.to_param}, valid_session
      assigns(:analisis_rsd).should eq(analisis_rsd)
    end
  end

  describe "GET new" do
    it "assigns a new analisis_rsd as @analisis_rsd" do
      get :new, {}, valid_session
      assigns(:analisis_rsd).should be_a_new(AnalisisRsd)
    end
  end

  describe "GET edit" do
    it "assigns the requested analisis_rsd as @analisis_rsd" do
      analisis_rsd = AnalisisRsd.create! valid_attributes
      get :edit, {:id => analisis_rsd.to_param}, valid_session
      assigns(:analisis_rsd).should eq(analisis_rsd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnalisisRsd" do
        expect {
          post :create, {:analisis_rsd => valid_attributes}, valid_session
        }.to change(AnalisisRsd, :count).by(1)
      end

      it "assigns a newly created analisis_rsd as @analisis_rsd" do
        post :create, {:analisis_rsd => valid_attributes}, valid_session
        assigns(:analisis_rsd).should be_a(AnalisisRsd)
        assigns(:analisis_rsd).should be_persisted
      end

      it "redirects to the created analisis_rsd" do
        post :create, {:analisis_rsd => valid_attributes}, valid_session
        response.should redirect_to(AnalisisRsd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved analisis_rsd as @analisis_rsd" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnalisisRsd.any_instance.stub(:save).and_return(false)
        post :create, {:analisis_rsd => { "fecha_extraccion" => "invalid value" }}, valid_session
        assigns(:analisis_rsd).should be_a_new(AnalisisRsd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnalisisRsd.any_instance.stub(:save).and_return(false)
        post :create, {:analisis_rsd => { "fecha_extraccion" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested analisis_rsd" do
        analisis_rsd = AnalisisRsd.create! valid_attributes
        # Assuming there are no other analisis_rsds in the database, this
        # specifies that the AnalisisRsd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnalisisRsd.any_instance.should_receive(:update_attributes).with({ "fecha_extraccion" => "2013-10-02" })
        put :update, {:id => analisis_rsd.to_param, :analisis_rsd => { "fecha_extraccion" => "2013-10-02" }}, valid_session
      end

      it "assigns the requested analisis_rsd as @analisis_rsd" do
        analisis_rsd = AnalisisRsd.create! valid_attributes
        put :update, {:id => analisis_rsd.to_param, :analisis_rsd => valid_attributes}, valid_session
        assigns(:analisis_rsd).should eq(analisis_rsd)
      end

      it "redirects to the analisis_rsd" do
        analisis_rsd = AnalisisRsd.create! valid_attributes
        put :update, {:id => analisis_rsd.to_param, :analisis_rsd => valid_attributes}, valid_session
        response.should redirect_to(analisis_rsd)
      end
    end

    describe "with invalid params" do
      it "assigns the analisis_rsd as @analisis_rsd" do
        analisis_rsd = AnalisisRsd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnalisisRsd.any_instance.stub(:save).and_return(false)
        put :update, {:id => analisis_rsd.to_param, :analisis_rsd => { "fecha_extraccion" => "invalid value" }}, valid_session
        assigns(:analisis_rsd).should eq(analisis_rsd)
      end

      it "re-renders the 'edit' template" do
        analisis_rsd = AnalisisRsd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnalisisRsd.any_instance.stub(:save).and_return(false)
        put :update, {:id => analisis_rsd.to_param, :analisis_rsd => { "fecha_extraccion" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested analisis_rsd" do
      analisis_rsd = AnalisisRsd.create! valid_attributes
      expect {
        delete :destroy, {:id => analisis_rsd.to_param}, valid_session
      }.to change(AnalisisRsd, :count).by(-1)
    end

    it "redirects to the analisis_rsds list" do
      analisis_rsd = AnalisisRsd.create! valid_attributes
      delete :destroy, {:id => analisis_rsd.to_param}, valid_session
      response.should redirect_to(analisis_rsds_url)
    end
  end

end
