require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductoresController do

  # This should return the minimal set of attributes required to create a valid
  # Productor. As you add validations to Productor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all productores as @productores" do
      productor = Productor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:productores).should eq([productor])
    end
  end

  describe "GET show" do
    it "assigns the requested productor as @productor" do
      productor = Productor.create! valid_attributes
      get :show, {:id => productor.to_param}, valid_session
      assigns(:productor).should eq(productor)
    end
  end

  describe "GET new" do
    it "assigns a new productor as @productor" do
      get :new, {}, valid_session
      assigns(:productor).should be_a_new(Productor)
    end
  end

  describe "GET edit" do
    it "assigns the requested productor as @productor" do
      productor = Productor.create! valid_attributes
      get :edit, {:id => productor.to_param}, valid_session
      assigns(:productor).should eq(productor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Productor" do
        expect {
          post :create, {:productor => valid_attributes}, valid_session
        }.to change(Productor, :count).by(1)
      end

      it "assigns a newly created productor as @productor" do
        post :create, {:productor => valid_attributes}, valid_session
        assigns(:productor).should be_a(Productor)
        assigns(:productor).should be_persisted
      end

      it "redirects to the created productor" do
        post :create, {:productor => valid_attributes}, valid_session
        response.should redirect_to(Productor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved productor as @productor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productor.any_instance.stub(:save).and_return(false)
        post :create, {:productor => { "nombre" => "invalid value" }}, valid_session
        assigns(:productor).should be_a_new(Productor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productor.any_instance.stub(:save).and_return(false)
        post :create, {:productor => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested productor" do
        productor = Productor.create! valid_attributes
        # Assuming there are no other productores in the database, this
        # specifies that the Productor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Productor.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => productor.to_param, :productor => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested productor as @productor" do
        productor = Productor.create! valid_attributes
        put :update, {:id => productor.to_param, :productor => valid_attributes}, valid_session
        assigns(:productor).should eq(productor)
      end

      it "redirects to the productor" do
        productor = Productor.create! valid_attributes
        put :update, {:id => productor.to_param, :productor => valid_attributes}, valid_session
        response.should redirect_to(productor)
      end
    end

    describe "with invalid params" do
      it "assigns the productor as @productor" do
        productor = Productor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productor.any_instance.stub(:save).and_return(false)
        put :update, {:id => productor.to_param, :productor => { "nombre" => "invalid value" }}, valid_session
        assigns(:productor).should eq(productor)
      end

      it "re-renders the 'edit' template" do
        productor = Productor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productor.any_instance.stub(:save).and_return(false)
        put :update, {:id => productor.to_param, :productor => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested productor" do
      productor = Productor.create! valid_attributes
      expect {
        delete :destroy, {:id => productor.to_param}, valid_session
      }.to change(Productor, :count).by(-1)
    end

    it "redirects to the productores list" do
      productor = Productor.create! valid_attributes
      delete :destroy, {:id => productor.to_param}, valid_session
      response.should redirect_to(productores_url)
    end
  end

end
